### ISSUE TITLE
Why it is called Rubik's Cube?

### ISSUE THREAD

**Issue by TodorBalabanov** [vitchyr/Genetic-Algorithms-and-Rubiks-Cube#1]
Excuse me for the asking, but why the project is related with the Rubik's Cube when there is no source code related with the cube?

**Comment by vitchyr** [comment]
I'm not sure since it'd been a while. But if I recall correctly, initially we were going to use the genetic algorithm to solve Rubik's cubes. We ended up switching to nonograms, and I guess we never changed the project name.

**Comment by TodorBalabanov** [comment]
It was interesting for me, because I did exactly Rubik's Cube GA solver: [RubiksCubeGeneticAlgorithmsSolver](https://github.com/TodorBalabanov/RubiksCubeGeneticAlgorithmsSolver)

If it is not so big compilation for you would you consider to update the repository name and the project description? Your project is very interesting and I am sure more people will find it easier if the description and the name correspond to the real source code.

**Comment by abunickabhi** [comment]
Nonogram is fun , but the way the cube works is quite different from nonogram,

so can GA be implemented on Rubiks Cube

**Comment by abunickabhi** [comment]
[https://arxiv.org/pdf/1805.07470.pdf](url)
